version: "3"
services:
        apache:
                image: wendelhime/curtobacterium_services:latest 
                deploy:
                        replicas: 2 
                        resources:
                                limits:
                                        cpus: "0.9"
                                        memory: 400M
                        restart_policy:
                                condition: on-failure
                ports:
                        - "80:80"
                        - "5432:5432"
                networks:
                        - webnet
networks:
        webnet:
